spring:
  application:
    name: mate
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: MATE
    password: MATE
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mate/**/dao/mapper/*Mapper.xml